version: "3.4"

services:
  database:
    container_name: database
    image: postgres
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: "landev"
      POSTGRES_PASSWORD: "password1234"
      POSTGRES_DB: "landev"
  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    restart: always
    expose:
      - 1080
  api:
    container_name: api
    image: quay.io/areafiftylan/lancie-api
    restart: always
    ports:
      - 8082:8080
  frontend:
    container_name: frontend
    image: quay.io/areafiftylan/lancie-frontend-beta
    restart: always
    ports:
      - 8080:8080
  admin:
    container_name: admin
    image: quay.io/areafiftylan/lancie-admin
    restart: always
    ports:
      - 8081:8080
