version: '3.6'

services:
  database:
    image: mariadb:latest
    volumes:
      - ./database:/var/lib/mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pyplanet
      MYSQL_USER: pyplanet
      MYSQL_PASSWORD: pyplanet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute="SHOW DATABASES;"
      interval: 60s
      timeout: 2s
      retries: 1
      start_period: 15s
  server:
    build: ./build-server
    restart: on-failure
    depends_on:
      - database
    environment:
      SERVER_TITLE: "TMStadium"
      SERVER_NAME: "AreaFiftyLAN"
    ports:
      - "2350:2350/tcp"
      - "2350:2350/udp"
      - "3450:3450/tcp"
      - "3450:3450/udp"
    expose:
      - 5005
    volumes:
      - ./cfg_server.xml:/home/server/tm_server/UserData/Config/cfg_server.xml:Z
      - ./cfg_tracklist.xml:/home/server/tm_server/UserData/Maps/MatchSettings/cfg_tracklist.xml:Z
      - ./maps:/home/server/tm_server/UserData/Maps/Campaigns:Z
      - ./packs:/home/server/tm_server/UserData/Packs:Z
      - ./modes:/home/server/tm_server/UserData/Modes:Z
  controller:
    image: harha/trackmania-server-docker:pyplanet
    restart: on-failure
    depends_on:
      - database
      - server
    volumes:
      - ./pyplanet/settings:/home/server/pyplanet/settings:Z

